{% set name = "csxtools" %}
{% set version = "0.1.16" %}
{% set sha256 = "dae027e8548734bad1baa88d95307cd21e9957ccacdc62b4b15ae7162a562be8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II-CSX/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - databroker
    - ipython
    - ipywidgets
    - matplotlib
    - pims >=0.3.3
    - tzlocal
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - csxtools
    - csxtools.ext
    - csxtools.ext.fastccd
    - csxtools.ext.image
    - csxtools.ext.phocount

about:
  home: https://github.com/NSLS-II-CSX/csxtools
  license: BSD 3-clause
  license_file: LICENSE.txt
  summary: Useful python tools for NSLS-II CSX (23-ID)
  doc_url: http://nsls-ii-csx.github.io/csxtools
  dev_url: https://github.com/NSLS-II-CSX/csxtools
